---
- name: add deploy user
  user: name=deploy shell=/bin/bash append=yes state=present groups="sudo,vagrant"

- name: set up authorized_keys for the deploy user
  authorized_key: user=deploy key="{{ item }}"
  with_file:
    - public_keys/patrick-vine
