---
- hosts: all
  remote_user: deploy

  tasks:
    - include: tasks/deploy_install_ruby.yml
    - include: tasks/deploy_application.yml
    - include: tasks/deploy_puma.yml

  vars_files:
    - vars/vars.yml


